### ISSUE TITLE
huffc doesn't compile contracts (no MAIN)

### ISSUE THREAD

**Issue by Divide-By-0** [whitenois3/huff-snark-verifier#6]
I get this error when compiling on step 3: 
```
Error: Missing Macro Definition For "MAIN"
-> ./emailVerifier.huff
```

**Comment by clabby** [comment]
The verifier library that this tool generates does not come with a `MAIN` macro - you are meant to implement it yourself. See the wrapper examples within the tests for an example.

Be cognizant of the [memory assumptions](https://github.com/whitenois3/huff-snark-verifier/blob/main/src/contracts/VerifierTemplate.huff#L8-L51) laid out by the verifier while doing so 😄
